### ISSUE TITLE
SSLErrror: unable to get data using pyniva

### ISSUE THREAD

**Issue by lisapro** [NIVANorge/pyniva#29]
Examples of error messages: 

requests.exceptions.SSLError: HTTPSConnectionPool(host='ferrybox-api.niva.no', port=443): Max retries exceeded with url: /v1/metaflow/?ttype=vessel (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ferrybox-api.niva.no', port=443): Max retries exceeded with url: /v1/metaflow/?ttype=vessel (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by haakondr** [comment]
SSL certificates expired. We forgot to fix this in the ferrybox API.

Updated ssl certificates for the following:

- api-test.niva.no (nivatest)
- ferrybox-api.niva.no (nivaprod)
- api.niva.no (nivaprod)

Try again now, hopefully it should work now
